name = "Purple Potato"
license = "MIT"
licenselink = "https://github.com/ethanwood17/purple-potato/blob/master/LICENSE.md"
description = "Based on the Dusky Neon Theme"
source_repo = "https://github.com/ethanwood17/purple-potato.git"
tags = ["Responsive", "Blog", "Google analytics", "Disqus", "Clean", "Tags", "Minimal", "Custom Themes", "Minimalist", "Simple", "Starter", "Dark"]
features = ["blog"]
min_version = 0.27
[author]
    name = "Ethan Wood"
    homepage = ""
[original]
    author="Zane C. Bowers-Hadley"
    homepage="https://github.com/VVelox/hugo-dusky-neon-potato"
    repo="https://github.com/VVelox/hugo-dusky-neon-potato.git"
